# mongo-express.yml
version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true    
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mongodb
      

  mongodb:
    image: mongo
    container_name: mongodb
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - db:/data/db  

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
  #     - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  default:
    name: mongo-express-network

volumes:
  db:    